#
GET  http://localhost:8080

###
POST http://localhost:8080

###
GET http://localhost:8080/dsTivi

###
GET http://localhost:8080/dsDienthoai

###
GET http://localhost:8080/Cuahang

###
GET http://localhost:8080/dsHocsinh

###
GET http://localhost:8080/dsNguoidung

###
GET http://localhost:8080/dsMathang

###
POST http://localhost:8080/ThemNguoidung
Content-Type: application/json

{
    "Ma_so": "QL_100",
    "Ho_ten": "Nguyen Anh Tai",
}

###
POST http://localhost:8080/Lienhe

###
GET http://localhost:8080/TIVI_2.png